#!/usr/bin/env bash
# gen-env.sh — generate .env from current shell environment.
#
# Usage:
#   ./scripts/gen-env.sh              # writes .env in current directory
#   ./scripts/gen-env.sh .env.staging # writes to a custom path
#
# Any variable already exported in your shell takes precedence over the
# defaults shown below.  Variables that have no value and no default are
# written as empty (compose will leave them unset in the container).

set -euo pipefail

DEST="${1:-.env}"

# Resolve dynamic defaults from the current shell
_UID="$(id -u)"
_GID="$(id -g)"
_PODMAN_SOCK="/run/user/${_UID}/podman/podman.sock"
_PROJECT_DIR="$(pwd)"
_DATA_DIR="${_PROJECT_DIR}/data"

# Helper: print   KEY=value   using the env var if set, otherwise the fallback
e() {
  local key="$1"
  local default="${2:-}"
  local val="${!key:-$default}"
  printf '%s=%s\n' "$key" "$val"
}

cat > "$DEST" <<EOF
# Generated by scripts/gen-env.sh on $(date -u '+%Y-%m-%d %T UTC')
# Edit values as needed, then keep this file out of git.

# =============================================================================
# Host identity
# =============================================================================
$(e UID  "$_UID")
$(e GID  "$_GID")

# =============================================================================
# Paths
# =============================================================================
$(e PODMAN_SOCKET_PATH       "$_PODMAN_SOCK")
$(e MASTER_PROJECT_DIR       "$_PROJECT_DIR")
$(e MASTER_DATA_DIR          "${MASTER_DATA_DIR:-${_DATA_DIR}/master}")

# =============================================================================
# Master image
# =============================================================================
$(e MASTER_RUNTIME_IMAGE     "codex-slack-v2.11")
$(e MASTER_AGENT_BASE_IMAGE  "codex-slack-v2.11")

# =============================================================================
# Master — git identity
# =============================================================================
$(e MASTER_GIT_USER_NAME     "codex-slack")
$(e MASTER_GIT_USER_EMAIL    "codex-slack@example.com")

# =============================================================================
# Master — auth paths
# =============================================================================
$(e MASTER_CODEX_AUTH_JSON_PATH  "${HOME}/.codex/auth.json")
$(e MASTER_SSH_AUTH_SOCK_PATH    "${SSH_AUTH_SOCK:-}")
$(e MASTER_SSH_KNOWN_HOSTS_PATH  "${HOME}/.ssh/known_hosts")

# =============================================================================
# Master — frontends & channels
# =============================================================================
$(e MASTER_FRONTENDS         "slack,discord")
$(e MASTER_ADMIN_CHANNELS    "")
$(e DISCORD_ADMIN_CHANNELS   "")

# =============================================================================
# Master — Slack credentials
# =============================================================================
$(e SLACK_BOT_TOKEN          "")
$(e SLACK_APP_TOKEN          "")

# =============================================================================
# Master — Discord credentials
# =============================================================================
$(e DISCORD_BOT_TOKEN        "")

# =============================================================================
# Master — API keys
# =============================================================================
$(e OPENAI_API_KEY            "")
$(e GH_TOKEN                  "")
$(e ANTHROPIC_API_KEY         "")
$(e CLAUDE_CODE_OAUTH_TOKEN   "")

# =============================================================================
# Master — runtime tunables
# =============================================================================
$(e MASTER_REGISTRY_PATH                   "data/master/agents.json")
$(e MASTER_DRY_RUN                         "false")
$(e MASTER_AGENT_TIMEOUT_SECONDS           "0")
$(e MASTER_COMMAND_RATE_LIMIT_COUNT        "20")
$(e MASTER_COMMAND_RATE_LIMIT_WINDOW_SECONDS "60")
$(e MASTER_DEFAULT_AGENT_ADAPTER           "codex")
$(e MASTER_AGENT_COMMAND_TEMPLATE         "codex exec --dangerously-bypass-approvals-and-sandbox -")
$(e MASTER_CODEX_COMMAND_TEMPLATE         "codex exec --dangerously-bypass-approvals-and-sandbox resume --last -")
$(e MASTER_CLAUDE_COMMAND_TEMPLATE        "claude -p --dangerously-skip-permissions")

# =============================================================================
# CD daemon — image tracking
# =============================================================================
$(e CD_IMAGE                 "ghcr.io/pandazxx/codex-slack-master")
$(e CD_IMAGE_TAG             "latest")
$(e CD_CONTAINER_NAME        "codex-slack-master")

# =============================================================================
# CD daemon — compose settings
# =============================================================================
$(e CD_COMPOSE_FILE          "/opt/codex-slack/docker-compose.master-agent.example.yml")
$(e CD_COMPOSE_SERVICE       "codex-slack-master")
$(e CD_COMPOSE_BINARY        "docker compose")
$(e CD_ENV_FILE              "/opt/codex-slack/.env")
$(e CD_STATE_FILE            "/opt/codex-slack/data/cd/state.json")

# =============================================================================
# CD daemon — behaviour
# =============================================================================
$(e CD_POLL_INTERVAL_SECONDS        "300")
$(e CD_HEALTH_CHECK_DELAY_SECONDS   "30")
$(e CD_ROLLBACK_ON_FAILURE          "true")
$(e CD_DRY_RUN                      "false")

# =============================================================================
# CD daemon — notifications (leave empty to disable)
# =============================================================================
$(e CD_NOTIFY_SLACK_WEBHOOK_URL    "")
$(e CD_NOTIFY_DISCORD_WEBHOOK_URL  "")
EOF

echo "Written: $DEST"
