"""Internal REST endpoints for the orchestration MCP server.

Called by the in-container orchestrate MCP process over HTTP; not part of the
public API surface. Endpoints per topic:

  POST .../orchestrate/delegate      — create a task, queue or dispatch the assignee's first prompt
  POST .../orchestrate/ask           — stage a clarifying question to the dispatcher or user
  POST .../orchestrate/submit_result — stage a result envelope from the assignee
  POST .../orchestrate/answer_question — stage an answer from the dispatcher to the assignee
  POST .../orchestrate/accept_result — accept the assignee's result, close the task
  GET  .../orchestrate/tasks         — list task rows for the UI

Turn re-entry (phase b):

  process_turn_end() is called from the MQTT /response handler after
  _save_agent_response completes.  It dispatches all staged rows for the
  completed prompt_message_id, then routes the free-text response per §7.

Startup scan:

  dispatch_undispatched_staged_rows() is called at startup to re-dispatch any
  staged rows whose turn's /response was already saved but the dispatch was
  interrupted by a master restart.
"""
from __future__ import annotations

import asyncio
import json
import logging
import threading
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

from .db import get_connection
from .orchestration import (
    MAX_DELEGATION_DEPTH,
    MAX_TASKS_PER_ROOT,
    IllegalTransition,
    apply_transition,
    detect_cycle,
    get_effective_max_delegation_depth,
    get_effective_max_tasks_per_root,
    get_topic_lock,
    validate_envelope,
)
from .staffs import resolve_staff

LOGGER = logging.getLogger(__name__)

router = APIRouter(
    prefix="/workspaces/{workspace_id}/topics/{topic_id}/orchestrate",
    tags=["orchestrate"],
)

tasks_router = APIRouter(
    prefix="/workspaces/{workspace_id}/topics/{topic_id}/orchestrate",
    tags=["orchestrate"],
)


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# ── Caller identity + token verification ──────────────────────────────────────

def _verify_caller_identity(
    conn,
    caller_message_id: str,
    caller_staff: str,
    topic_id: str,
) -> None:
    """Bind the caller's claimed identity to a genuinely dispatched prompt row.

    Phase-b binding: the caller_message_id row must (a) exist, (b) belong to
    this topic, and (c) when the row carries identity fields, at least one must
    match caller_staff.  Token verification happens separately via
    _verify_dispatch_token when a dispatch_token is present in the request.

    Rows without identity fields (legacy user messages, synthetic test rows
    without receiver_name/agent_name) bypass the name-match and are accepted.
    """
    row = conn.execute(
        "SELECT topic_id, receiver_name, agent_name FROM messages WHERE id = ?",
        (caller_message_id,),
    ).fetchone()
    if row is None:
        LOGGER.warning(
            "orchestration.guard_hit guard=caller_mismatch task_id=None topic_id=%s"
            " reason=unknown_message_id",
            topic_id,
        )
        raise HTTPException(422, "caller_mismatch")
    if row["topic_id"] != topic_id:
        LOGGER.warning(
            "orchestration.guard_hit guard=caller_mismatch task_id=None topic_id=%s"
            " reason=wrong_topic",
            topic_id,
        )
        raise HTTPException(422, "caller_mismatch")
    receiver_name = row["receiver_name"]
    agent_name = row["agent_name"]
    if (receiver_name is not None or agent_name is not None) and caller_staff not in (
        receiver_name,
        agent_name,
    ):
        LOGGER.warning(
            "orchestration.guard_hit guard=caller_mismatch task_id=None topic_id=%s"
            " reason=name_mismatch caller=%s",
            topic_id,
            caller_staff,
        )
        raise HTTPException(422, "caller_mismatch")


def _verify_dispatch_token(
    conn,
    caller_message_id: str,
    dispatch_token: str,
    topic_id: str,
) -> None:
    """Verify that the dispatch_token matches the token stored on the prompt row.

    The token is a per-dispatch UUID generated by dispatch_to_staff and stored
    in messages.dispatch_token.  A mismatch indicates a forged or replayed call.
    """
    row = conn.execute(
        "SELECT dispatch_token FROM messages WHERE id = ?",
        (caller_message_id,),
    ).fetchone()
    if row is None or row["dispatch_token"] != dispatch_token:
        LOGGER.warning(
            "orchestration.guard_hit guard=invalid_dispatch_token topic_id=%s"
            " caller_message_id=%s",
            topic_id,
            caller_message_id,
        )
        raise HTTPException(403, "invalid_dispatch_token")


# ── Helper: workspace lookup for a topic ────────────────────────────────────

def _get_workspace_id(conn, topic_id: str) -> str | None:
    row = conn.execute("SELECT workspace_id FROM topics WHERE id = ?", (topic_id,)).fetchone()
    return row["workspace_id"] if row else None


# ── Staged dispatch helpers ──────────────────────────────────────────────────

def _stage_dispatch(
    conn,
    prompt_message_id: str,
    topic_id: str,
    sender_name: str,
    receiver_kind: str,
    receiver_name: str | None,
    task_id: str,
    kind: str,
    body: str,
) -> str:
    """Insert a staged_dispatches row and return its id."""
    row_id = str(uuid.uuid4())
    conn.execute(
        "INSERT INTO staged_dispatches"
        " (id, prompt_message_id, topic_id, sender_name, receiver_kind, receiver_name,"
        "  task_id, kind, body, created_at)"
        " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
        (
            row_id, prompt_message_id, topic_id, sender_name, receiver_kind, receiver_name,
            task_id, kind, body, _now(),
        ),
    )
    return row_id


def _stamp_dispatched(conn, row_id: str) -> None:
    conn.execute(
        "UPDATE staged_dispatches SET dispatched_at = ? WHERE id = ?",
        (_now(), row_id),
    )


# ── Prompt-text builder ──────────────────────────────────────────────────────

_ASSIGNEE_INSTRUCTION_FOOTER = (
    "\n\n---\n"
    "You are the assignee of the task above. Use the `ask_sender` tool "
    "for any clarifying questions — do not ask in plain text. "
    "When finished, submit your result via `submit_result(status, summary, artifacts)`. "
    "Your plain reply text is not delivered as a question and will not reach anyone."
)

_ANSWER_DELIVERY_FOOTER = (
    "\n\n---\n"
    "The answer above was provided by your dispatcher. "
    "Continue working on the task and finish with `submit_result(status, summary, artifacts)`."
)


def _build_prompt(goal: str, acceptance_criteria: str, context: str | None) -> str:
    parts = []
    if context:
        parts.append(f"**Context:**\n{context}")
    parts.append(f"**Goal:**\n{goal}")
    parts.append(f"**Acceptance criteria:**\n{acceptance_criteria}")
    return "\n\n".join(parts) + _ASSIGNEE_INSTRUCTION_FOOTER


def _build_judgment_prompt(task: object, result_summary: str, result_status: str) -> str:
    goal = task["goal"]  # type: ignore[index]
    criteria = task["acceptance_criteria"] or ""
    return (
        f"Task (id={task['id']!r}, goal={goal!r}) completed by @{task['assignee_name']}.\n\n"  # type: ignore[index]
        f"**Result status:** {result_status}\n\n"
        f"**Result summary:**\n{result_summary}\n\n"
        f"**Acceptance criteria:**\n{criteria}\n\n"
        "Please call `accept_result` if the result meets the criteria.  "
        "In phase (b) rejection and give-up are not yet available — "
        "if you need changes, provide feedback as free text (it will be recorded) "
        "and the task will remain in its current state pending further action."
    )


# ── Endpoint models ──────────────────────────────────────────────────────────

class DelegateIn(BaseModel):
    caller_staff: str
    caller_message_id: str
    dispatch_token: str
    staff: str
    goal: str
    acceptance_criteria: str
    context: str | None = None


class DelegateOut(BaseModel):
    task_id: str
    state: str
    queued_position: int | None = None


class AskIn(BaseModel):
    caller_staff: str
    caller_message_id: str
    dispatch_token: str
    question: str


class AskOut(BaseModel):
    message_id: str
    task_state: str


class SubmitResultIn(BaseModel):
    caller_staff: str
    caller_message_id: str
    dispatch_token: str
    status: str  # 'completed' | 'failed'
    summary: str
    artifacts: list[dict] | None = None


class SubmitResultOut(BaseModel):
    task_id: str
    state: str


class AnswerQuestionIn(BaseModel):
    caller_staff: str
    caller_message_id: str
    dispatch_token: str
    task_id: str
    answer: str


class AnswerQuestionOut(BaseModel):
    task_id: str
    state: str


class AcceptResultIn(BaseModel):
    caller_staff: str
    caller_message_id: str
    dispatch_token: str
    task_id: str


class AcceptResultOut(BaseModel):
    task_id: str
    state: str


class TaskOut(BaseModel):
    id: str
    topic_id: str
    root_task_id: str
    parent_task_id: str | None
    depth: int
    dispatcher_kind: str
    dispatcher_name: str | None
    assignee_name: str
    goal: str
    acceptance_criteria: str | None
    state: str
    failure_score: float
    result_summary: str | None
    result_artifacts: str | None
    result_status: str | None
    created_at: str
    updated_at: str
    closed_at: str | None


# ── Common workspace/topic validation ────────────────────────────────────────

def _assert_workspace_and_topic(conn, workspace_id: str, topic_id: str) -> None:
    if conn.execute(
        "SELECT id FROM workspaces WHERE id = ? AND archived_at IS NULL",
        (workspace_id,),
    ).fetchone() is None:
        raise HTTPException(404, "workspace not found")
    if conn.execute(
        "SELECT id FROM topics WHERE id = ? AND workspace_id = ? AND archived_at IS NULL",
        (topic_id, workspace_id),
    ).fetchone() is None:
        raise HTTPException(404, "topic not found")


# ── delegate_task ──────────────────────────────────────────────────────────────

@router.post("/delegate", response_model=DelegateOut, status_code=200)
async def delegate_task(
    workspace_id: str,
    topic_id: str,
    body: DelegateIn,
    request: Request,
) -> DelegateOut:
    app_state = request.app.state
    db_path = app_state.db_path

    conn = get_connection(db_path)
    try:
        _assert_workspace_and_topic(conn, workspace_id, topic_id)
        _verify_caller_identity(conn, body.caller_message_id, body.caller_staff, topic_id)
        _verify_dispatch_token(conn, body.caller_message_id, body.dispatch_token, topic_id)

        if body.caller_staff == body.staff:
            LOGGER.warning(
                "orchestration.guard_hit guard=self_delegation task_id=None topic_id=%s",
                topic_id,
            )
            raise HTTPException(422, "self_delegation")

        target_staff = resolve_staff(conn, body.staff, workspace_id, topic_id)
        if target_staff is None:
            LOGGER.warning(
                "orchestration.guard_hit guard=unknown_staff task_id=None topic_id=%s",
                topic_id,
            )
            raise HTTPException(404, "staff not found")

        effective_max_depth = get_effective_max_delegation_depth(conn, workspace_id)
        effective_max_root = get_effective_max_tasks_per_root(conn, workspace_id)

        caller_task_row = None
        caller_depth = 0
        prompt_row = conn.execute(
            "SELECT task_id FROM messages WHERE id = ?", (body.caller_message_id,)
        ).fetchone()
        if prompt_row and prompt_row["task_id"]:
            caller_task_row = conn.execute(
                "SELECT * FROM tasks WHERE id = ?", (prompt_row["task_id"],)
            ).fetchone()
            if caller_task_row:
                caller_depth = caller_task_row["depth"]

        if caller_depth >= effective_max_depth:
            LOGGER.warning(
                "orchestration.guard_hit guard=depth_exceeded task_id=%s topic_id=%s",
                caller_task_row["id"] if caller_task_row else None,
                topic_id,
            )
            raise HTTPException(422, "depth_exceeded")

        new_depth = caller_depth + 1

        root_task_id: str | None = None
        parent_task_id: str | None = None
        dispatcher_kind = "staff"
        dispatcher_name = body.caller_staff

        if caller_task_row:
            root_task_id = caller_task_row["root_task_id"]
            parent_task_id = caller_task_row["id"]
            count = conn.execute(
                "SELECT COUNT(*) FROM tasks WHERE root_task_id = ?", (root_task_id,)
            ).fetchone()[0]
            if count >= effective_max_root:
                LOGGER.warning(
                    "orchestration.guard_hit guard=fan_out_exceeded task_id=%s topic_id=%s",
                    caller_task_row["id"],
                    topic_id,
                )
                raise HTTPException(422, "fan_out_exceeded")

        if caller_task_row:
            ancestors = []
            ancestor_id: str | None = caller_task_row["parent_task_id"]
            while ancestor_id:
                row = conn.execute(
                    "SELECT assignee_name, dispatcher_name, parent_task_id FROM tasks WHERE id = ?",
                    (ancestor_id,),
                ).fetchone()
                if row is None:
                    break
                ancestors.append(row)
                ancestor_id = row["parent_task_id"]
            if detect_cycle(ancestors, body.staff):
                LOGGER.warning(
                    "orchestration.guard_hit guard=cycle_detected task_id=%s topic_id=%s",
                    caller_task_row["id"],
                    topic_id,
                )
                raise HTTPException(422, "cycle_detected")

        try:
            validate_envelope(
                sender_kind="staff",
                sender_name=body.caller_staff,
                receiver_kind="staff",
                receiver_name=body.staff,
                task_id="pending",
            )
        except ValueError as exc:
            LOGGER.warning(
                "orchestration.guard_hit guard=%s task_id=%s topic_id=%s",
                str(exc),
                caller_task_row["id"] if caller_task_row else None,
                topic_id,
            )
            raise HTTPException(422, str(exc)) from exc

        task_id = str(uuid.uuid4())
        if root_task_id is None:
            root_task_id = task_id
        now = _now()

        conn.execute(
            "INSERT INTO tasks"
            " (id, topic_id, root_task_id, parent_task_id, depth,"
            "  dispatcher_kind, dispatcher_name, assignee_name,"
            "  goal, acceptance_criteria, state, failure_score,"
            "  created_at, updated_at)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'submitted', 0.0, ?, ?)",
            (
                task_id, topic_id, root_task_id, parent_task_id, new_depth,
                dispatcher_kind, dispatcher_name, body.staff,
                body.goal, body.acceptance_criteria, now, now,
            ),
        )
        conn.commit()
    finally:
        conn.close()

    topic_lock = get_topic_lock(topic_id)
    acquired = topic_lock.acquire(blocking=False)
    if not acquired:
        # Another task is in-flight on this topic — queue this one.
        # queued_position is advisory/approximate: it is counted after insertion and
        # may not match the final dispatch order if concurrent delegates race.
        queued_position = _count_queued_tasks(db_path, topic_id)
        LOGGER.info(
            "orchestration.task_queued task_id=%s topic_id=%s position=%d",
            task_id, topic_id, queued_position,
        )
        return DelegateOut(task_id=task_id, state="queued", queued_position=queued_position)

    # Lock acquired — dispatch the assignee's first prompt immediately.
    try:
        await _dispatch_task_first_prompt(
            app_state=app_state,
            workspace_id=workspace_id,
            topic_id=topic_id,
            task_id=task_id,
            target_staff=target_staff,
            body=body,
            db_path=db_path,
        )
    except Exception:
        topic_lock.release()
        raise

    return DelegateOut(task_id=task_id, state="working")


def _count_queued_tasks(db_path: str, topic_id: str) -> int:
    conn = get_connection(db_path)
    try:
        return conn.execute(
            "SELECT COUNT(*) FROM tasks WHERE topic_id = ? AND state = 'submitted'",
            (topic_id,),
        ).fetchone()[0]
    finally:
        conn.close()


async def _dispatch_task_first_prompt(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    task_id: str,
    target_staff,
    body: DelegateIn,
    db_path: str,
) -> None:
    """Dispatch the assignee's first prompt and transition task to 'working'."""
    prompt_text = _build_prompt(body.goal, body.acceptance_criteria, body.context)

    from .dispatch import dispatch_to_staff
    await dispatch_to_staff(
        app_state=app_state,
        workspace_id=workspace_id,
        topic_id=topic_id,
        staff=target_staff,
        prompt_text=prompt_text,
        sender="event",
        sender_kind="staff",
        sender_name=body.caller_staff,
        receiver_kind="staff",
        receiver_name=body.staff,
        task_id=task_id,
        reply_to_message_id=body.caller_message_id,
    )

    state_conn = get_connection(db_path)
    try:
        state_conn.execute(
            "UPDATE tasks SET state = 'working', updated_at = ? WHERE id = ?",
            (_now(), task_id),
        )
        state_conn.commit()
    finally:
        state_conn.close()


# ── ask_sender ────────────────────────────────────────────────────────────────

@router.post("/ask", response_model=AskOut, status_code=200)
async def ask_sender(
    workspace_id: str,
    topic_id: str,
    body: AskIn,
    request: Request,
) -> AskOut:
    app_state = request.app.state
    db_path = app_state.db_path

    conn = get_connection(db_path)
    try:
        _assert_workspace_and_topic(conn, workspace_id, topic_id)
        _verify_caller_identity(conn, body.caller_message_id, body.caller_staff, topic_id)
        _verify_dispatch_token(conn, body.caller_message_id, body.dispatch_token, topic_id)

        prompt_row = conn.execute(
            "SELECT task_id FROM messages WHERE id = ?", (body.caller_message_id,)
        ).fetchone()

        task_row = None
        if prompt_row and prompt_row["task_id"]:
            task_row = conn.execute(
                "SELECT * FROM tasks WHERE id = ?", (prompt_row["task_id"],)
            ).fetchone()

        task_state = "n/a"
        receiver_kind = "user"
        receiver_name = None

        if task_row:
            caller_is_dispatcher = (body.caller_staff == task_row["dispatcher_name"])

            if caller_is_dispatcher:
                # The dispatcher is asking — route UP to whoever dispatched the dispatcher.
                # For v1 depth-1 tasks the dispatcher has no parent task, so its sender is
                # always the user.  For deeper trees we look up the parent task's dispatcher.
                parent_task_id = task_row["parent_task_id"]
                if parent_task_id:
                    parent_task = conn.execute(
                        "SELECT dispatcher_kind, dispatcher_name FROM tasks WHERE id = ?",
                        (parent_task_id,),
                    ).fetchone()
                    if parent_task:
                        receiver_kind = parent_task["dispatcher_kind"]
                        receiver_name = parent_task["dispatcher_name"]
                    else:
                        receiver_kind = "user"
                        receiver_name = None
                else:
                    receiver_kind = "user"
                    receiver_name = None
            else:
                # Caller is the assignee — ask the task's dispatcher.
                receiver_kind = task_row["dispatcher_kind"]
                receiver_name = task_row["dispatcher_name"]

            # Safety guard: never allow a question whose receiver equals the caller.
            # If the routing above still resolves to the caller itself, escalate to user.
            if receiver_name == body.caller_staff:
                LOGGER.warning(
                    "orchestration.guard_hit guard=self_question_prevented task_id=%s"
                    " topic_id=%s caller=%s computed_receiver=%s — routing to user",
                    task_row["id"], topic_id, body.caller_staff, receiver_name,
                )
                receiver_kind = "user"
                receiver_name = None

            try:
                apply_transition(task_row["state"], "ask_sender")
            except IllegalTransition:
                LOGGER.warning(
                    "orchestration.guard_hit guard=illegal_transition task_id=%s"
                    " topic_id=%s current_state=%s event=ask_sender",
                    task_row["id"], topic_id, task_row["state"],
                )
                raise HTTPException(409, "illegal_transition")
            task_state = "input-required"

        # Generate the question message UUID and insert the row immediately for all receiver kinds.
        # This makes the message visible in the DB as soon as ask_sender returns, regardless of
        # whether the receiver is a user or a staff member.
        # For staff receivers: a staged dispatch is also queued so process_turn_end fires MQTT
        # at turn-end (dispatch_to_staff is called with insert_row=False to skip re-inserting).
        # sender='agent' for user-receiver questions (visible chat bubble);
        # sender='event' for staff-receiver questions (matches dispatch_to_staff convention).
        message_id = str(uuid.uuid4())
        dispatch_token_for_question = str(uuid.uuid4())
        question_sender = "agent" if receiver_kind == "user" else "event"

        conn.execute(
            "INSERT INTO messages"
            " (id, topic_id, sender, agent_name, text, transcript, usage_json, attachments_json,"
            "  silent, created_at,"
            "  sender_kind, sender_name, receiver_kind, receiver_name,"
            "  task_id, reply_to_message_id, dispatch_token)"
            " VALUES (?, ?, ?, ?, ?, NULL, NULL, NULL, 0, ?,"
            "         'staff', ?, ?, ?, ?, ?, ?)",
            (
                message_id, topic_id, question_sender, body.caller_staff, body.question, _now(),
                body.caller_staff, receiver_kind, receiver_name,
                task_row["id"] if task_row else None,
                body.caller_message_id,
                dispatch_token_for_question,
            ),
        )

        if task_row:
            conn.execute(
                "UPDATE tasks SET state = 'input-required', updated_at = ? WHERE id = ?",
                (_now(), task_row["id"]),
            )
            # For staff receivers: stage the question dispatch so process_turn_end publishes
            # MQTT when the caller's turn ends. The message row is already written above;
            # dispatch_to_staff will be called with insert_row=False to avoid a duplicate.
            if receiver_kind == "staff":
                _stage_dispatch(
                    conn,
                    prompt_message_id=body.caller_message_id,
                    topic_id=topic_id,
                    sender_name=body.caller_staff,
                    receiver_kind=receiver_kind,
                    receiver_name=receiver_name,
                    task_id=task_row["id"],
                    kind="question",
                    body=json.dumps({
                        "message_id": message_id,
                        "text": body.question,
                    }),
                )
        conn.commit()
    finally:
        conn.close()

    # Broadcast the question for user-receiver questions so the UI shows the bubble immediately.
    # For staff-receiver questions the broadcast happens when the staged dispatch fires
    # (inside dispatch_to_staff at turn-end).
    if receiver_kind == "user":
        await app_state.hub.broadcast("_global", {
            "type": "message",
            "topic_id": topic_id,
            "message_id": message_id,
            "sender": "agent",
            "agent_name": body.caller_staff,
            "text": body.question,
            "transcript": None,
            "attachments": [],
            "sender_kind": "staff",
            "sender_name": body.caller_staff,
            "receiver_kind": receiver_kind,
            "receiver_name": receiver_name,
            "task_id": task_row["id"] if task_row else None,
            "reply_to_message_id": body.caller_message_id,
        })

    return AskOut(message_id=message_id, task_state=task_state)


# ── submit_result ─────────────────────────────────────────────────────────────

@router.post("/submit_result", response_model=SubmitResultOut, status_code=200)
async def submit_result(
    workspace_id: str,
    topic_id: str,
    body: SubmitResultIn,
    request: Request,
) -> SubmitResultOut:
    db_path = request.app.state.db_path

    if body.status not in ("completed", "failed"):
        raise HTTPException(422, "invalid_status")

    conn = get_connection(db_path)
    try:
        _assert_workspace_and_topic(conn, workspace_id, topic_id)
        _verify_caller_identity(conn, body.caller_message_id, body.caller_staff, topic_id)
        _verify_dispatch_token(conn, body.caller_message_id, body.dispatch_token, topic_id)

        prompt_row = conn.execute(
            "SELECT task_id FROM messages WHERE id = ?", (body.caller_message_id,)
        ).fetchone()
        if not prompt_row or not prompt_row["task_id"]:
            LOGGER.warning(
                "orchestration.guard_hit guard=no_task_context task_id=None topic_id=%s"
                " endpoint=submit_result",
                topic_id,
            )
            raise HTTPException(422, "no_task_context")

        task_row = conn.execute(
            "SELECT * FROM tasks WHERE id = ?", (prompt_row["task_id"],)
        ).fetchone()
        if task_row is None:
            raise HTTPException(404, "task not found")

        if task_row["assignee_name"] != body.caller_staff:
            LOGGER.warning(
                "orchestration.guard_hit guard=not_assignee task_id=%s topic_id=%s",
                task_row["id"], topic_id,
            )
            raise HTTPException(403, "not_assignee")

        try:
            apply_transition(task_row["state"], "submit_result")
        except IllegalTransition:
            LOGGER.warning(
                "orchestration.guard_hit guard=illegal_transition task_id=%s topic_id=%s"
                " current_state=%s event=submit_result",
                task_row["id"], topic_id, task_row["state"],
            )
            raise HTTPException(409, "illegal_transition")

        artifacts_json = json.dumps(body.artifacts or [])

        # Remove any prior staged result for this prompt to implement last-call-wins.
        conn.execute(
            "DELETE FROM staged_dispatches"
            " WHERE prompt_message_id = ? AND kind = 'result_ready'",
            (body.caller_message_id,),
        )

        conn.execute(
            "UPDATE tasks SET result_summary = ?, result_artifacts = ?, result_status = ?,"
            " updated_at = ? WHERE id = ?",
            (body.summary, artifacts_json, body.status, _now(), task_row["id"]),
        )
        _stage_dispatch(
            conn,
            prompt_message_id=body.caller_message_id,
            topic_id=topic_id,
            sender_name=body.caller_staff,
            receiver_kind=task_row["dispatcher_kind"],
            receiver_name=task_row["dispatcher_name"],
            task_id=task_row["id"],
            kind="result_ready",
            body=json.dumps({
                "summary": body.summary,
                "status": body.status,
                "artifacts": body.artifacts or [],
            }),
        )
        conn.commit()
    finally:
        conn.close()

    return SubmitResultOut(task_id=prompt_row["task_id"], state="working")


# ── answer_question ────────────────────────────────────────────────────────────

@router.post("/answer_question", response_model=AnswerQuestionOut, status_code=200)
async def answer_question(
    workspace_id: str,
    topic_id: str,
    body: AnswerQuestionIn,
    request: Request,
) -> AnswerQuestionOut:
    db_path = request.app.state.db_path

    conn = get_connection(db_path)
    try:
        _assert_workspace_and_topic(conn, workspace_id, topic_id)
        _verify_caller_identity(conn, body.caller_message_id, body.caller_staff, topic_id)
        _verify_dispatch_token(conn, body.caller_message_id, body.dispatch_token, topic_id)

        task_row = conn.execute(
            "SELECT * FROM tasks WHERE id = ?", (body.task_id,)
        ).fetchone()
        if task_row is None:
            raise HTTPException(404, "task not found")

        if task_row["dispatcher_name"] != body.caller_staff:
            LOGGER.warning(
                "orchestration.guard_hit guard=not_dispatcher task_id=%s topic_id=%s",
                task_row["id"], topic_id,
            )
            raise HTTPException(403, "not_dispatcher")

        if task_row["state"] != "input-required":
            LOGGER.warning(
                "orchestration.guard_hit guard=illegal_transition task_id=%s topic_id=%s"
                " current_state=%s event=answer_question",
                task_row["id"], topic_id, task_row["state"],
            )
            raise HTTPException(409, "illegal_transition")

        _stage_dispatch(
            conn,
            prompt_message_id=body.caller_message_id,
            topic_id=topic_id,
            sender_name=body.caller_staff,
            receiver_kind="staff",
            receiver_name=task_row["assignee_name"],
            task_id=body.task_id,
            kind="answer",
            body=json.dumps({"answer": body.answer}),
        )
        conn.commit()
    finally:
        conn.close()

    # The task remains in 'input-required' at response time; the staged answer
    # dispatches at turn end (process_turn_end), at which point the task transitions
    # to 'working'.  Returning the actual current state keeps callers truthful.
    return AnswerQuestionOut(task_id=body.task_id, state="input-required")


# ── accept_result ──────────────────────────────────────────────────────────────

@router.post("/accept_result", response_model=AcceptResultOut, status_code=200)
async def accept_result(
    workspace_id: str,
    topic_id: str,
    body: AcceptResultIn,
    request: Request,
) -> AcceptResultOut:
    app_state = request.app.state
    db_path = app_state.db_path

    conn = get_connection(db_path)
    try:
        _assert_workspace_and_topic(conn, workspace_id, topic_id)
        _verify_caller_identity(conn, body.caller_message_id, body.caller_staff, topic_id)
        _verify_dispatch_token(conn, body.caller_message_id, body.dispatch_token, topic_id)

        task_row = conn.execute(
            "SELECT * FROM tasks WHERE id = ?", (body.task_id,)
        ).fetchone()
        if task_row is None:
            raise HTTPException(404, "task not found")

        if task_row["dispatcher_name"] != body.caller_staff:
            LOGGER.warning(
                "orchestration.guard_hit guard=not_dispatcher task_id=%s topic_id=%s",
                task_row["id"], topic_id,
            )
            raise HTTPException(403, "not_dispatcher")

        try:
            apply_transition(task_row["state"], "accept_result")
        except IllegalTransition:
            LOGGER.warning(
                "orchestration.guard_hit guard=illegal_transition task_id=%s topic_id=%s"
                " current_state=%s event=accept_result",
                task_row["id"], topic_id, task_row["state"],
            )
            raise HTTPException(409, "illegal_transition")

        now = _now()
        conn.execute(
            "UPDATE tasks SET state = 'completed', closed_at = ?, updated_at = ? WHERE id = ?",
            (now, now, body.task_id),
        )
        conn.commit()
    finally:
        conn.close()

    # Release the topic lock, then dispatch the next queued task (if any).
    # Awaiting _dispatch_next_queued is safe because it tries acquire(blocking=False);
    # if the queue is empty or another coroutine holds the lock it returns immediately.
    topic_lock = get_topic_lock(topic_id)
    try:
        topic_lock.release()
    except RuntimeError:
        pass  # already released — defensive guard only
    await _dispatch_next_queued(app_state, workspace_id, topic_id)

    return AcceptResultOut(task_id=body.task_id, state="completed")


# ── GET tasks ─────────────────────────────────────────────────────────────────

@tasks_router.get("/tasks", response_model=list[TaskOut], status_code=200)
def list_tasks(
    workspace_id: str,
    topic_id: str,
    request: Request,
) -> list[TaskOut]:
    conn = get_connection(request.app.state.db_path)
    try:
        _assert_workspace_and_topic(conn, workspace_id, topic_id)
        rows = conn.execute(
            "SELECT * FROM tasks WHERE topic_id = ? ORDER BY created_at",
            (topic_id,),
        ).fetchall()
        return [
            TaskOut(
                id=r["id"],
                topic_id=r["topic_id"],
                root_task_id=r["root_task_id"],
                parent_task_id=r["parent_task_id"],
                depth=r["depth"],
                dispatcher_kind=r["dispatcher_kind"],
                dispatcher_name=r["dispatcher_name"],
                assignee_name=r["assignee_name"],
                goal=r["goal"],
                acceptance_criteria=r["acceptance_criteria"],
                state=r["state"],
                failure_score=r["failure_score"],
                result_summary=r["result_summary"],
                result_artifacts=r["result_artifacts"],
                result_status=r["result_status"],
                created_at=r["created_at"],
                updated_at=r["updated_at"],
                closed_at=r["closed_at"],
            )
            for r in rows
        ]
    finally:
        conn.close()


# ── Turn re-entry: process_turn_end ──────────────────────────────────────────

async def process_turn_end(
    app_state,
    workspace_id: str,
    topic_id: str,
    prompt_message_id: str,
    reply_message_id: str,
    agent_name: str,
    reply_text: str,
    interrupt_reason: str | None,
) -> None:
    """Dispatch staged rows and route free text after an agent's turn completes.

    Called by the MQTT /response handler.  Implements design §7 turn re-entry.

    Interrupted/failed turns skip re-entry entirely — we leave the task state
    unchanged and rely on process restart / redelivery of the prompt to recover.
    """
    if interrupt_reason:
        LOGGER.info(
            "orchestration.turn_skipped reason=interrupted topic_id=%s"
            " prompt_message_id=%s interrupt_reason=%s",
            topic_id, prompt_message_id, interrupt_reason,
        )
        return

    db_path = app_state.db_path
    conn = get_connection(db_path)
    try:
        staged_rows = conn.execute(
            "SELECT * FROM staged_dispatches"
            " WHERE prompt_message_id = ? AND dispatched_at IS NULL"
            " ORDER BY created_at",
            (prompt_message_id,),
        ).fetchall()

        prompt_row = conn.execute(
            "SELECT task_id, sender_kind, sender_name FROM messages WHERE id = ?",
            (prompt_message_id,),
        ).fetchone()

        task_row = None
        if prompt_row and prompt_row["task_id"]:
            task_row = conn.execute(
                "SELECT * FROM tasks WHERE id = ?", (prompt_row["task_id"],)
            ).fetchone()
    finally:
        conn.close()

    # Determine the reply-to-sender receiver for the free-text response.
    # For assignee turns the receiver is the task's dispatcher (the staff that sent the task).
    # For dispatcher turns (judgment, answer-to-assignee question) the receiver is the
    # dispatcher's OWN sender — always the user for depth-1 tasks with no parent task.
    # A dispatcher's free text must NEVER route to the assignee.
    free_text_receiver_kind = "user"
    free_text_receiver_name: str | None = None
    if task_row:
        caller_is_task_dispatcher = (agent_name == task_row["dispatcher_name"])
        if caller_is_task_dispatcher:
            # Dispatcher turn: free text goes up to whoever sent the dispatcher.
            # For depth-1 tasks (no parent_task_id) the dispatcher's sender is the user.
            free_text_receiver_kind = "user"
            free_text_receiver_name = None
        else:
            # Assignee turn: free text goes to the task's dispatcher.
            free_text_receiver_kind = task_row["dispatcher_kind"]
            free_text_receiver_name = task_row["dispatcher_name"]

    staged_receiver_names = {
        r["receiver_name"] for r in staged_rows
        if r["receiver_kind"] == "staff"
    }

    # If no staged row was recorded and this was a delegated turn, apply implicit fallbacks.
    if not staged_rows and task_row:
        await _apply_implicit_fallback(
            app_state=app_state,
            workspace_id=workspace_id,
            topic_id=topic_id,
            task_row=task_row,
            prompt_message_id=prompt_message_id,
            reply_message_id=reply_message_id,
            agent_name=agent_name,
            reply_text=reply_text,
        )
        return

    # Dispatch each staged row in order.
    for staged in staged_rows:
        await _execute_staged_row(
            app_state=app_state,
            workspace_id=workspace_id,
            topic_id=topic_id,
            staged=staged,
            reply_message_id=reply_message_id,
            db_path=db_path,
        )

    # Route the free-text response.
    # If a staged message already targets the free-text receiver, mark the reply silent
    # (the structured content is the message of record per design §7).
    # Otherwise, if receiver is a staff, dispatch it; if receiver is user, it stays visible.
    if free_text_receiver_name in staged_receiver_names:
        _mark_reply_silent(db_path, reply_message_id)
    elif free_text_receiver_kind == "staff" and free_text_receiver_name:
        await _dispatch_free_text_to_staff(
            app_state=app_state,
            workspace_id=workspace_id,
            topic_id=topic_id,
            agent_name=agent_name,
            reply_text=reply_text,
            task_row=task_row,
            prompt_message_id=prompt_message_id,
            reply_message_id=reply_message_id,
            receiver_name=free_text_receiver_name,
        )


async def _apply_implicit_fallback(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    task_row,
    prompt_message_id: str,
    reply_message_id: str,
    agent_name: str,
    reply_text: str,
) -> None:
    """Handle a delegated turn that ended without calling the expected tool.

    Dispatched turn type is inferred from task state:
      - task is 'working' and agent is assignee → implicit submit_result
      - task is 'input-required' and agent is dispatcher (answering) → implicit answer
      - task is 'working' and agent is dispatcher (judgment turn after result_ready
        was dispatched in a prior turn) → judgment_missing guard_hit, no re-entry

    Design §4.3–4.4 (phase-b subset only): phase (c) adds scored-clarification.
    """
    db_path = app_state.db_path
    task_id = task_row["id"]

    # Re-read the task row to avoid acting on a stale snapshot (M-7).
    # master is the single writer of task state, so a fresh read is sufficient.
    fresh_conn = get_connection(db_path)
    try:
        fresh_task = fresh_conn.execute(
            "SELECT * FROM tasks WHERE id = ?", (task_id,)
        ).fetchone()
    finally:
        fresh_conn.close()

    if fresh_task is None:
        LOGGER.warning("orchestration.implicit_fallback_task_missing task_id=%s", task_id)
        return

    assignee = fresh_task["assignee_name"]
    dispatcher = fresh_task["dispatcher_name"]
    state = fresh_task["state"]

    if state == "working" and agent_name == assignee:
        # Implicit submit_result: use the reply text as the summary.
        LOGGER.info(
            "orchestration.implicit_result task_id=%s topic_id=%s agent=%s",
            task_id, topic_id, agent_name,
        )
        await _dispatch_judgment_turn(
            app_state=app_state,
            workspace_id=workspace_id,
            topic_id=topic_id,
            task_row=fresh_task,
            result_summary=reply_text,
            result_status="completed",
            reply_message_id=reply_message_id,
            db_path=db_path,
        )
    elif state == "input-required" and agent_name == dispatcher:
        # Implicit answer: use the reply text as the answer.
        LOGGER.info(
            "orchestration.implicit_answer task_id=%s topic_id=%s agent=%s",
            task_id, topic_id, agent_name,
        )
        await _dispatch_answer_to_assignee(
            app_state=app_state,
            workspace_id=workspace_id,
            topic_id=topic_id,
            task_row=fresh_task,
            answer=reply_text,
            sender_name=agent_name,
            reply_message_id=reply_message_id,
            db_path=db_path,
        )
    elif state == "working" and agent_name == dispatcher:
        # Judgment turn ended with no accept_result.  The reply text routes to the user
        # (the dispatcher's own sender for depth-1 tasks); task state is unchanged —
        # the task stays result-pending until the dispatcher accepts or rejects in a
        # future turn.  Phase (c) adds scored-clarification to the assignee;
        # phase (b) routes to user and logs the guard hit.
        LOGGER.warning(
            "orchestration.guard_hit guard=judgment_missing task_id=%s topic_id=%s"
            " reply_text=%.120r",
            task_id, topic_id, reply_text,
        )
        # The reply_message_id row is already visible to the user (sender='agent',
        # receiver derived from reply-to-sender = user).  No additional dispatch needed.


async def _execute_staged_row(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    staged,
    reply_message_id: str,
    db_path: str,
) -> None:
    """Execute one staged dispatch row and stamp it dispatched."""
    kind = staged["kind"]
    task_id = staged["task_id"]
    sender_name = staged["sender_name"]
    receiver_kind = staged["receiver_kind"]
    receiver_name = staged["receiver_name"]
    body_data = json.loads(staged["body"])

    conn = get_connection(db_path)
    try:
        task_row = conn.execute(
            "SELECT * FROM tasks WHERE id = ?", (task_id,)
        ).fetchone()
    finally:
        conn.close()

    if task_row is None:
        LOGGER.warning("orchestration.staged_task_missing task_id=%s", task_id)
        return

    # Stamp dispatched_at BEFORE calling dispatch_to_staff (C-4: at-most-once bias).
    # A crash after the stamp but before MQTT publish is recovered by the startup scan
    # re-delivering the prompt; a crash after publish but before stamp would double-dispatch
    # the judgment turn, which is worse.  On dispatch failure, best-effort clear the stamp.
    conn = get_connection(db_path)
    try:
        conn.execute(
            "UPDATE staged_dispatches SET dispatched_at = ? WHERE id = ?",
            (_now(), staged["id"]),
        )
        conn.commit()
    finally:
        conn.close()

    try:
        if kind == "question":
            # Deliver the already-saved question message to the staff receiver via MQTT.
            # The message row was written in ask_sender; we publish the prompt payload here
            # without creating a second row (eliminates the duplicate-message bug).
            if receiver_kind == "staff" and receiver_name:
                await _dispatch_question_to_staff(
                    app_state=app_state,
                    workspace_id=workspace_id,
                    topic_id=topic_id,
                    task_row=task_row,
                    question_message_id=body_data.get("message_id", ""),
                    question_text=body_data.get("text", ""),
                    sender_name=sender_name,
                    receiver_name=receiver_name,
                    reply_message_id=reply_message_id,
                    db_path=db_path,
                )

        elif kind == "answer":
            answer = body_data.get("answer", "")
            await _dispatch_answer_to_assignee(
                app_state=app_state,
                workspace_id=workspace_id,
                topic_id=topic_id,
                task_row=task_row,
                answer=answer,
                sender_name=sender_name,
                reply_message_id=reply_message_id,
                db_path=db_path,
            )

        elif kind == "result_ready":
            result_summary = body_data.get("summary", "")
            result_status = body_data.get("status", "completed")
            conn = get_connection(db_path)
            try:
                conn.execute(
                    "UPDATE tasks SET result_summary = ?, result_status = ?, updated_at = ?"
                    " WHERE id = ?",
                    (result_summary, result_status, _now(), task_id),
                )
                conn.commit()
            finally:
                conn.close()
            await _dispatch_judgment_turn(
                app_state=app_state,
                workspace_id=workspace_id,
                topic_id=topic_id,
                task_row=task_row,
                result_summary=result_summary,
                result_status=result_status,
                reply_message_id=reply_message_id,
                db_path=db_path,
            )
    except Exception:
        # Best-effort: clear the dispatch stamp so startup scan can retry on next restart.
        LOGGER.warning(
            "orchestration.staged_dispatch_failed staged_id=%s kind=%s task_id=%s"
            " — clearing dispatched_at for retry",
            staged["id"], kind, task_id,
        )
        try:
            _clear_conn = get_connection(db_path)
            try:
                _clear_conn.execute(
                    "UPDATE staged_dispatches SET dispatched_at = NULL WHERE id = ?",
                    (staged["id"],),
                )
                _clear_conn.commit()
            finally:
                _clear_conn.close()
        except Exception:
            LOGGER.warning(
                "orchestration.clear_dispatch_stamp_failed staged_id=%s", staged["id"]
            )
        raise


async def _dispatch_question_to_staff(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    task_row,
    question_message_id: str,
    question_text: str,
    sender_name: str,
    receiver_name: str,
    reply_message_id: str,
    db_path: str,
) -> None:
    """Publish the MQTT prompt for a question whose message row was already inserted by ask_sender.

    The question row is created at /ask time (immediately visible); this function only
    publishes the MQTT dispatch at turn-end so the receiving staff agent processes it.
    dispatch_to_staff is called with insert_row=False to skip re-inserting the row.
    """
    target_staff = _resolve_staff_for_topic(db_path, workspace_id, topic_id, receiver_name)
    if target_staff is None:
        LOGGER.warning(
            "orchestration.dispatch_failed reason=staff_not_found name=%s task_id=%s",
            receiver_name, task_row["id"],
        )
        return

    from .dispatch import dispatch_to_staff
    await dispatch_to_staff(
        app_state=app_state,
        workspace_id=workspace_id,
        topic_id=topic_id,
        staff=target_staff,
        prompt_text=question_text,
        sender="event",
        sender_kind="staff",
        sender_name=sender_name,
        receiver_kind="staff",
        receiver_name=receiver_name,
        task_id=task_row["id"],
        reply_to_message_id=reply_message_id,
        reuse_message_id=question_message_id,
        insert_row=False,
    )


async def _dispatch_answer_to_assignee(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    task_row,
    answer: str,
    sender_name: str,
    reply_message_id: str,
    db_path: str,
) -> None:
    """Dispatch an answer to the assignee and transition task to 'working'."""
    assignee_name = task_row["assignee_name"]
    target_staff = _resolve_staff_for_topic(db_path, workspace_id, topic_id, assignee_name)
    if target_staff is None:
        LOGGER.warning(
            "orchestration.dispatch_failed reason=staff_not_found name=%s task_id=%s",
            assignee_name, task_row["id"],
        )
        return

    conn = get_connection(db_path)
    try:
        conn.execute(
            "UPDATE tasks SET state = 'working', updated_at = ? WHERE id = ?",
            (_now(), task_row["id"]),
        )
        conn.commit()
    finally:
        conn.close()

    from .dispatch import dispatch_to_staff
    await dispatch_to_staff(
        app_state=app_state,
        workspace_id=workspace_id,
        topic_id=topic_id,
        staff=target_staff,
        prompt_text=answer + _ANSWER_DELIVERY_FOOTER,
        sender="event",
        sender_kind="staff",
        sender_name=sender_name,
        receiver_kind="staff",
        receiver_name=assignee_name,
        task_id=task_row["id"],
        reply_to_message_id=reply_message_id,
    )


async def _dispatch_judgment_turn(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    task_row,
    result_summary: str,
    result_status: str,
    reply_message_id: str,
    db_path: str,
) -> None:
    """Dispatch the judgment turn prompt to the dispatcher."""
    dispatcher_kind = task_row["dispatcher_kind"]
    dispatcher_name = task_row["dispatcher_name"]

    if dispatcher_kind == "user":
        # No agent turn to dispatch — the result lands in the topic for the user to see.
        LOGGER.info(
            "orchestration.result_to_user task_id=%s topic_id=%s",
            task_row["id"], topic_id,
        )
        return

    target_staff = _resolve_staff_for_topic(db_path, workspace_id, topic_id, dispatcher_name)
    if target_staff is None:
        LOGGER.warning(
            "orchestration.dispatch_failed reason=staff_not_found name=%s task_id=%s",
            dispatcher_name, task_row["id"],
        )
        return

    judgment_prompt = _build_judgment_prompt(task_row, result_summary, result_status)
    from .dispatch import dispatch_to_staff
    await dispatch_to_staff(
        app_state=app_state,
        workspace_id=workspace_id,
        topic_id=topic_id,
        staff=target_staff,
        prompt_text=judgment_prompt,
        sender="event",
        sender_kind="staff",
        sender_name=task_row["assignee_name"],
        receiver_kind="staff",
        receiver_name=dispatcher_name,
        task_id=task_row["id"],
        reply_to_message_id=reply_message_id,
    )


def _mark_reply_silent(db_path: str, reply_message_id: str) -> None:
    """Mark the reply message silent=1 in the DB (free text duplicates structured output)."""
    conn = get_connection(db_path)
    try:
        conn.execute(
            "UPDATE messages SET silent = 1 WHERE id = ?", (reply_message_id,)
        )
        conn.commit()
    finally:
        conn.close()


async def _dispatch_free_text_to_staff(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    agent_name: str,
    reply_text: str,
    task_row,
    prompt_message_id: str,
    reply_message_id: str,
    receiver_name: str,
) -> None:
    """Dispatch the free-text reply to the staff dispatcher (phase-a-style plain reply inside task)."""
    db_path = app_state.db_path
    target_staff = _resolve_staff_for_topic(db_path, workspace_id, topic_id, receiver_name)
    if target_staff is None:
        LOGGER.warning(
            "orchestration.dispatch_failed reason=staff_not_found name=%s task_id=%s",
            receiver_name, task_row["id"] if task_row else None,
        )
        return

    from .dispatch import dispatch_to_staff
    await dispatch_to_staff(
        app_state=app_state,
        workspace_id=workspace_id,
        topic_id=topic_id,
        staff=target_staff,
        prompt_text=reply_text,
        sender="event",
        sender_kind="staff",
        sender_name=agent_name,
        receiver_kind="staff",
        receiver_name=receiver_name,
        task_id=task_row["id"] if task_row else None,
        reply_to_message_id=reply_message_id,
    )


def _resolve_staff_for_topic(db_path: str, workspace_id: str, topic_id: str, name: str):
    conn = get_connection(db_path)
    try:
        return resolve_staff(conn, name, workspace_id, topic_id)
    finally:
        conn.close()


# ── Next-queued dispatch ──────────────────────────────────────────────────────

async def _dispatch_next_queued(app_state, workspace_id: str, topic_id: str) -> None:
    """Dispatch the oldest submitted (queued) task for a topic, if any.

    Called after the current in-flight task completes and the lock has been
    released.  Serialised by the per-topic threading.Lock: we try to acquire
    it; if another coroutine already grabbed it, they will handle the queue.
    """
    db_path = app_state.db_path
    topic_lock = get_topic_lock(topic_id)
    acquired = topic_lock.acquire(blocking=False)
    if not acquired:
        return  # another dispatch already in progress

    try:
        conn = get_connection(db_path)
        try:
            # SELECT and UPDATE in one connection/transaction to avoid TOCTOU between
            # the existence check and the state stamp (M-6).
            task_row = conn.execute(
                "SELECT * FROM tasks WHERE topic_id = ? AND state = 'submitted'"
                " ORDER BY created_at LIMIT 1",
                (topic_id,),
            ).fetchone()
            if task_row is None:
                # No queued task — release the lock before returning (C-1).
                topic_lock.release()
                return

            ws_row = conn.execute(
                "SELECT id FROM workspaces WHERE id = ("
                " SELECT workspace_id FROM topics WHERE id = ?)",
                (topic_id,),
            ).fetchone()
            ws_id = ws_row["id"] if ws_row else workspace_id

            target_staff = resolve_staff(conn, task_row["assignee_name"], ws_id, topic_id)
            staff_found = target_staff is not None

            if staff_found:
                conn.execute(
                    "UPDATE tasks SET state = 'working', updated_at = ? WHERE id = ?",
                    (_now(), task_row["id"]),
                )
                conn.commit()
        finally:
            conn.close()

        if not staff_found:
            LOGGER.warning(
                "orchestration.dispatch_failed reason=staff_not_found name=%s task_id=%s",
                task_row["assignee_name"], task_row["id"],
            )
            topic_lock.release()
            return

        # Queued tasks have never been dispatched, so no prompt message exists yet.
        # Reconstruct the prompt from the task's goal and acceptance_criteria columns,
        # mirroring _dispatch_task_first_prompt.
        prompt_text = _build_prompt(
            task_row["goal"],
            task_row["acceptance_criteria"] or "",
            None,
        )

        from .dispatch import dispatch_to_staff
        await dispatch_to_staff(
            app_state=app_state,
            workspace_id=ws_id,
            topic_id=topic_id,
            staff=target_staff,
            prompt_text=prompt_text,
            sender="event",
            sender_kind="staff",
            sender_name=task_row["dispatcher_name"] or "",
            receiver_kind="staff",
            receiver_name=task_row["assignee_name"],
            task_id=task_row["id"],
            reply_to_message_id=None,
        )
        LOGGER.info(
            "orchestration.queued_task_dispatched task_id=%s topic_id=%s",
            task_row["id"], topic_id,
        )
    except Exception:
        LOGGER.exception("orchestration.dispatch_next_queued_error topic_id=%s", topic_id)
        try:
            topic_lock.release()
        except RuntimeError:
            pass


# ── Startup scan ──────────────────────────────────────────────────────────────

def dispatch_undispatched_staged_rows(app_state, loop: asyncio.AbstractEventLoop) -> None:
    """Dispatch any staged rows whose turn's /response was saved before a master restart.

    Called once at startup from the lifespan context.  For each undispatched
    staged row, we check whether the prompt's /response message already exists;
    if yes, the turn completed but the dispatch was interrupted, so we re-dispatch
    it now.  If the response does not exist, redelivery of the MQTT prompt will
    handle it naturally.
    """
    db_path = app_state.db_path
    conn = get_connection(db_path)
    try:
        rows = conn.execute(
            "SELECT sd.*, m.topic_id AS prompt_topic_id"
            " FROM staged_dispatches sd"
            " JOIN messages m ON m.id = sd.prompt_message_id"
            " WHERE sd.dispatched_at IS NULL",
        ).fetchall()
        # For each undispatched row, find the agent response that already closed the turn
        # so we can pass the correct reply_message_id (M-1: preserves reply chain).
        orphaned: list[tuple] = []
        for r in rows:
            response_row = conn.execute(
                "SELECT id FROM messages WHERE reply_to_message_id = ? AND sender = 'agent'"
                " ORDER BY created_at DESC LIMIT 1",
                (r["prompt_message_id"],),
            ).fetchone()
            if response_row:
                orphaned.append((r, response_row["id"]))
    finally:
        conn.close()

    if not orphaned:
        return

    LOGGER.info("orchestration.startup_scan orphaned_staged=%d", len(orphaned))
    for staged, reply_message_id in orphaned:
        topic_id = staged["topic_id"]

        # M-2: skip topics whose lock is held — an in-flight turn will advance them.
        topic_lock = get_topic_lock(topic_id)
        if not topic_lock.acquire(blocking=False):
            LOGGER.info(
                "orchestration.startup_scan skipped_locked topic_id=%s staged_id=%s",
                topic_id, staged["id"],
            )
            continue

        ws_conn = get_connection(db_path)
        try:
            ws_row = ws_conn.execute(
                "SELECT workspace_id FROM topics WHERE id = ?", (topic_id,)
            ).fetchone()
            workspace_id = ws_row["workspace_id"] if ws_row else ""
        finally:
            ws_conn.close()

        asyncio.run_coroutine_threadsafe(
            _startup_execute_and_release(
                app_state=app_state,
                workspace_id=workspace_id,
                topic_id=topic_id,
                staged=staged,
                reply_message_id=reply_message_id,
                db_path=db_path,
                topic_lock=topic_lock,
            ),
            loop,
        )


async def _startup_execute_and_release(
    *,
    app_state,
    workspace_id: str,
    topic_id: str,
    staged,
    reply_message_id: str,
    db_path: str,
    topic_lock: threading.Lock,
) -> None:
    """Execute a single orphaned staged row and release the topic lock (M-2, C-3)."""
    try:
        await _execute_staged_row(
            app_state=app_state,
            workspace_id=workspace_id,
            topic_id=topic_id,
            staged=staged,
            reply_message_id=reply_message_id,
            db_path=db_path,
        )
    finally:
        try:
            topic_lock.release()
        except RuntimeError:
            pass
